'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization

<Assembly: EdmSchemaAttribute()>
Namespace DevExpressMvcApplication1.Models
	#Region "Contexts"

	''' <summary>
	''' No Metadata Documentation available.
	''' </summary>
	Partial Public Class NorthwindEntities
		Inherits ObjectContext
		#Region "Constructors"

		''' <summary>
		''' Initializes a new NorthwindEntities object using the connection string found in the 'NorthwindEntities' section of the application configuration file.
		''' </summary>
		Public Sub New()
			MyBase.New("name=NorthwindEntities", "NorthwindEntities")
			Me.ContextOptions.LazyLoadingEnabled = True
			OnContextCreated()
		End Sub

		''' <summary>
		''' Initialize a new NorthwindEntities object.
		''' </summary>
		Public Sub New(ByVal connectionString As String)
			MyBase.New(connectionString, "NorthwindEntities")
			Me.ContextOptions.LazyLoadingEnabled = True
			OnContextCreated()
		End Sub

		''' <summary>
		''' Initialize a new NorthwindEntities object.
		''' </summary>
		Public Sub New(ByVal connection As EntityConnection)
			MyBase.New(connection, "NorthwindEntities")
			Me.ContextOptions.LazyLoadingEnabled = True
			OnContextCreated()
		End Sub

		#End Region

		#Region "Partial Methods"

		Partial Private Sub OnContextCreated()
		End Sub

		#End Region

		#Region "ObjectSet Properties"

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		Public ReadOnly Property Products() As ObjectSet(Of Product)
			Get
				If (_Products Is Nothing) Then
					_Products = MyBase.CreateObjectSet(Of Product)("Products")
				End If
				Return _Products
			End Get
		End Property
		Private _Products As ObjectSet(Of Product)

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		Public ReadOnly Property Shippers() As ObjectSet(Of Shipper)
			Get
				If (_Shippers Is Nothing) Then
					_Shippers = MyBase.CreateObjectSet(Of Shipper)("Shippers")
				End If
				Return _Shippers
			End Get
		End Property
		Private _Shippers As ObjectSet(Of Shipper)

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		Public ReadOnly Property Suppliers() As ObjectSet(Of Supplier)
			Get
				If (_Suppliers Is Nothing) Then
					_Suppliers = MyBase.CreateObjectSet(Of Supplier)("Suppliers")
				End If
				Return _Suppliers
			End Get
		End Property
		Private _Suppliers As ObjectSet(Of Supplier)

		#End Region

		#Region "AddTo Methods"

		''' <summary>
		''' Deprecated Method for adding a new object to the Products EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
		''' </summary>
		Public Sub AddToProducts(ByVal product As Product)
			MyBase.AddObject("Products", product)
		End Sub

		''' <summary>
		''' Deprecated Method for adding a new object to the Shippers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
		''' </summary>
		Public Sub AddToShippers(ByVal shipper As Shipper)
			MyBase.AddObject("Shippers", shipper)
		End Sub

		''' <summary>
		''' Deprecated Method for adding a new object to the Suppliers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
		''' </summary>
		Public Sub AddToSuppliers(ByVal supplier As Supplier)
			MyBase.AddObject("Suppliers", supplier)
		End Sub

		#End Region

	End Class

	#End Region

	#Region "Entities"

	''' <summary>
	''' No Metadata Documentation available.
	''' </summary>
	<EdmEntityTypeAttribute(NamespaceName:="NorthwindModel", Name:="Product"), Serializable(), DataContractAttribute(IsReference:=True)> _
	Partial Public Class Product
		Inherits EntityObject
		#Region "Factory Method"

		''' <summary>
		''' Create a new Product object.
		''' </summary>
		''' <param name="productID">Initial value of the ProductID property.</param>
		''' <param name="productName">Initial value of the ProductName property.</param>
		''' <param name="discontinued">Initial value of the Discontinued property.</param>
		Public Shared Function CreateProduct(ByVal productID As Global.System.Int32, ByVal productName As Global.System.String, ByVal discontinued As Global.System.Boolean) As Product
			Dim product As New Product()
			product.ProductID = productID
			product.ProductName = productName
			product.Discontinued = discontinued
			Return product
		End Function

		#End Region

		#Region "Primitive Properties"

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), DataMemberAttribute()> _
		Public Property ProductID() As Global.System.Int32
			Get
				Return _ProductID
			End Get
			Set(ByVal value As System.Int32)
				If _ProductID <> value Then
					OnProductIDChanging(value)
					ReportPropertyChanging("ProductID")
					_ProductID = StructuralObject.SetValidValue(value)
					ReportPropertyChanged("ProductID")
					OnProductIDChanged()
				End If
			End Set
		End Property
		Private _ProductID As Global.System.Int32
		Partial Private Sub OnProductIDChanging(ByVal value As Global.System.Int32)
		End Sub
		Partial Private Sub OnProductIDChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), DataMemberAttribute()> _
		Public Property ProductName() As Global.System.String
			Get
				Return _ProductName
			End Get
			Set(ByVal value As System.String)
				If _ProductName <> value Then
					OnProductNameChanging(value)
					ReportPropertyChanging("ProductName")
					_ProductName = StructuralObject.SetValidValue(value, False)
					ReportPropertyChanged("ProductName")
					OnProductNameChanged()
				End If
			End Set
		End Property
		Private _ProductName As Global.System.String
		Partial Private Sub OnProductNameChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnProductNameChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
		Public Property SupplierID() As Global.System.Int32?
			Get
				Return _SupplierID
			End Get
			Set(ByVal value? As System.Int32)
				OnSupplierIDChanging(value)
				ReportPropertyChanging("SupplierID")
				_SupplierID = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("SupplierID")
				OnSupplierIDChanged()
			End Set
		End Property
		Private _SupplierID? As Global.System.Int32
		Partial Private Sub OnSupplierIDChanging(ByVal value? As Global.System.Int32)
		End Sub
		Partial Private Sub OnSupplierIDChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
		Public Property CategoryID() As Global.System.Int32?
			Get
				Return _CategoryID
			End Get
			Set(ByVal value? As System.Int32)
				OnCategoryIDChanging(value)
				ReportPropertyChanging("CategoryID")
				_CategoryID = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("CategoryID")
				OnCategoryIDChanged()
			End Set
		End Property
		Private _CategoryID? As Global.System.Int32
		Partial Private Sub OnCategoryIDChanging(ByVal value? As Global.System.Int32)
		End Sub
		Partial Private Sub OnCategoryIDChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
		Public Property QuantityPerUnit() As Global.System.String
			Get
				Return _QuantityPerUnit
			End Get
			Set(ByVal value As System.String)
				OnQuantityPerUnitChanging(value)
				ReportPropertyChanging("QuantityPerUnit")
				_QuantityPerUnit = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("QuantityPerUnit")
				OnQuantityPerUnitChanged()
			End Set
		End Property
		Private _QuantityPerUnit As Global.System.String
		Partial Private Sub OnQuantityPerUnitChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnQuantityPerUnitChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
		Public Property UnitPrice() As Global.System.Decimal?
			Get
				Return _UnitPrice
			End Get
			Set(ByVal value? As System.Decimal)
				OnUnitPriceChanging(value)
				ReportPropertyChanging("UnitPrice")
				_UnitPrice = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("UnitPrice")
				OnUnitPriceChanged()
			End Set
		End Property
		Private _UnitPrice? As Global.System.Decimal
		Partial Private Sub OnUnitPriceChanging(ByVal value? As Global.System.Decimal)
		End Sub
		Partial Private Sub OnUnitPriceChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
		Public Property UnitsInStock() As Global.System.Int16?
			Get
				Return _UnitsInStock
			End Get
			Set(ByVal value? As System.Int16)
				OnUnitsInStockChanging(value)
				ReportPropertyChanging("UnitsInStock")
				_UnitsInStock = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("UnitsInStock")
				OnUnitsInStockChanged()
			End Set
		End Property
		Private _UnitsInStock? As Global.System.Int16
		Partial Private Sub OnUnitsInStockChanging(ByVal value? As Global.System.Int16)
		End Sub
		Partial Private Sub OnUnitsInStockChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
		Public Property UnitsOnOrder() As Global.System.Int16?
			Get
				Return _UnitsOnOrder
			End Get
			Set(ByVal value? As System.Int16)
				OnUnitsOnOrderChanging(value)
				ReportPropertyChanging("UnitsOnOrder")
				_UnitsOnOrder = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("UnitsOnOrder")
				OnUnitsOnOrderChanged()
			End Set
		End Property
		Private _UnitsOnOrder? As Global.System.Int16
		Partial Private Sub OnUnitsOnOrderChanging(ByVal value? As Global.System.Int16)
		End Sub
		Partial Private Sub OnUnitsOnOrderChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
		Public Property ReorderLevel() As Global.System.Int16?
			Get
				Return _ReorderLevel
			End Get
			Set(ByVal value? As System.Int16)
				OnReorderLevelChanging(value)
				ReportPropertyChanging("ReorderLevel")
				_ReorderLevel = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("ReorderLevel")
				OnReorderLevelChanged()
			End Set
		End Property
		Private _ReorderLevel? As Global.System.Int16
		Partial Private Sub OnReorderLevelChanging(ByVal value? As Global.System.Int16)
		End Sub
		Partial Private Sub OnReorderLevelChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), DataMemberAttribute()> _
		Public Property Discontinued() As Global.System.Boolean
			Get
				Return _Discontinued
			End Get
			Set(ByVal value As System.Boolean)
				If _Discontinued <> value Then
					OnDiscontinuedChanging(value)
					ReportPropertyChanging("Discontinued")
					_Discontinued = StructuralObject.SetValidValue(value)
					ReportPropertyChanged("Discontinued")
					OnDiscontinuedChanged()
				End If
			End Set
		End Property
		Private _Discontinued As Global.System.Boolean
		Partial Private Sub OnDiscontinuedChanging(ByVal value As Global.System.Boolean)
		End Sub
		Partial Private Sub OnDiscontinuedChanged()
		End Sub

		#End Region


	End Class

	''' <summary>
	''' No Metadata Documentation available.
	''' </summary>
	<EdmEntityTypeAttribute(NamespaceName:="NorthwindModel", Name:="Shipper"), Serializable(), DataContractAttribute(IsReference:=True)> _
	Partial Public Class Shipper
		Inherits EntityObject
		#Region "Factory Method"

		''' <summary>
		''' Create a new Shipper object.
		''' </summary>
		''' <param name="shipperID">Initial value of the ShipperID property.</param>
		''' <param name="companyName">Initial value of the CompanyName property.</param>
		Public Shared Function CreateShipper(ByVal shipperID As Global.System.Int32, ByVal companyName As Global.System.String) As Shipper
			Dim shipper As New Shipper()
			shipper.ShipperID = shipperID
			shipper.CompanyName = companyName
			Return shipper
		End Function

		#End Region

		#Region "Primitive Properties"

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), DataMemberAttribute()> _
		Public Property ShipperID() As Global.System.Int32
			Get
				Return _ShipperID
			End Get
			Set(ByVal value As System.Int32)
				If _ShipperID <> value Then
					OnShipperIDChanging(value)
					ReportPropertyChanging("ShipperID")
					_ShipperID = StructuralObject.SetValidValue(value)
					ReportPropertyChanged("ShipperID")
					OnShipperIDChanged()
				End If
			End Set
		End Property
		Private _ShipperID As Global.System.Int32
		Partial Private Sub OnShipperIDChanging(ByVal value As Global.System.Int32)
		End Sub
		Partial Private Sub OnShipperIDChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), DataMemberAttribute()> _
		Public Property CompanyName() As Global.System.String
			Get
				Return _CompanyName
			End Get
			Set(ByVal value As System.String)
				If _CompanyName <> value Then
					OnCompanyNameChanging(value)
					ReportPropertyChanging("CompanyName")
					_CompanyName = StructuralObject.SetValidValue(value, False)
					ReportPropertyChanged("CompanyName")
					OnCompanyNameChanged()
				End If
			End Set
		End Property
		Private _CompanyName As Global.System.String
		Partial Private Sub OnCompanyNameChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnCompanyNameChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
		Public Property Phone() As Global.System.String
			Get
				Return _Phone
			End Get
			Set(ByVal value As System.String)
				OnPhoneChanging(value)
				ReportPropertyChanging("Phone")
				_Phone = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("Phone")
				OnPhoneChanged()
			End Set
		End Property
		Private _Phone As Global.System.String
		Partial Private Sub OnPhoneChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnPhoneChanged()
		End Sub

		#End Region


	End Class

	''' <summary>
	''' No Metadata Documentation available.
	''' </summary>
	<EdmEntityTypeAttribute(NamespaceName:="NorthwindModel", Name:="Supplier"), Serializable(), DataContractAttribute(IsReference:=True)> _
	Partial Public Class Supplier
		Inherits EntityObject
		#Region "Factory Method"

		''' <summary>
		''' Create a new Supplier object.
		''' </summary>
		''' <param name="supplierID">Initial value of the SupplierID property.</param>
		''' <param name="companyName">Initial value of the CompanyName property.</param>
		Public Shared Function CreateSupplier(ByVal supplierID As Global.System.Int32, ByVal companyName As Global.System.String) As Supplier
			Dim supplier As New Supplier()
			supplier.SupplierID = supplierID
			supplier.CompanyName = companyName
			Return supplier
		End Function

		#End Region

		#Region "Primitive Properties"

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), DataMemberAttribute()> _
		Public Property SupplierID() As Global.System.Int32
			Get
				Return _SupplierID
			End Get
			Set(ByVal value As System.Int32)
				If _SupplierID <> value Then
					OnSupplierIDChanging(value)
					ReportPropertyChanging("SupplierID")
					_SupplierID = StructuralObject.SetValidValue(value)
					ReportPropertyChanged("SupplierID")
					OnSupplierIDChanged()
				End If
			End Set
		End Property
		Private _SupplierID As Global.System.Int32
		Partial Private Sub OnSupplierIDChanging(ByVal value As Global.System.Int32)
		End Sub
		Partial Private Sub OnSupplierIDChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), DataMemberAttribute()> _
		Public Property CompanyName() As Global.System.String
			Get
				Return _CompanyName
			End Get
			Set(ByVal value As System.String)
				If _CompanyName <> value Then
					OnCompanyNameChanging(value)
					ReportPropertyChanging("CompanyName")
					_CompanyName = StructuralObject.SetValidValue(value, False)
					ReportPropertyChanged("CompanyName")
					OnCompanyNameChanged()
				End If
			End Set
		End Property
		Private _CompanyName As Global.System.String
		Partial Private Sub OnCompanyNameChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnCompanyNameChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
		Public Property ContactName() As Global.System.String
			Get
				Return _ContactName
			End Get
			Set(ByVal value As System.String)
				OnContactNameChanging(value)
				ReportPropertyChanging("ContactName")
				_ContactName = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("ContactName")
				OnContactNameChanged()
			End Set
		End Property
		Private _ContactName As Global.System.String
		Partial Private Sub OnContactNameChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnContactNameChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
		Public Property ContactTitle() As Global.System.String
			Get
				Return _ContactTitle
			End Get
			Set(ByVal value As System.String)
				OnContactTitleChanging(value)
				ReportPropertyChanging("ContactTitle")
				_ContactTitle = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("ContactTitle")
				OnContactTitleChanged()
			End Set
		End Property
		Private _ContactTitle As Global.System.String
		Partial Private Sub OnContactTitleChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnContactTitleChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
		Public Property Address() As Global.System.String
			Get
				Return _Address
			End Get
			Set(ByVal value As System.String)
				OnAddressChanging(value)
				ReportPropertyChanging("Address")
				_Address = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("Address")
				OnAddressChanged()
			End Set
		End Property
		Private _Address As Global.System.String
		Partial Private Sub OnAddressChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnAddressChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
		Public Property City() As Global.System.String
			Get
				Return _City
			End Get
			Set(ByVal value As System.String)
				OnCityChanging(value)
				ReportPropertyChanging("City")
				_City = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("City")
				OnCityChanged()
			End Set
		End Property
		Private _City As Global.System.String
		Partial Private Sub OnCityChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnCityChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
		Public Property Region() As Global.System.String
			Get
				Return _Region
			End Get
			Set(ByVal value As System.String)
				OnRegionChanging(value)
				ReportPropertyChanging("Region")
				_Region = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("Region")
				OnRegionChanged()
			End Set
		End Property
		Private _Region As Global.System.String
		Partial Private Sub OnRegionChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnRegionChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
		Public Property PostalCode() As Global.System.String
			Get
				Return _PostalCode
			End Get
			Set(ByVal value As System.String)
				OnPostalCodeChanging(value)
				ReportPropertyChanging("PostalCode")
				_PostalCode = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("PostalCode")
				OnPostalCodeChanged()
			End Set
		End Property
		Private _PostalCode As Global.System.String
		Partial Private Sub OnPostalCodeChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnPostalCodeChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
		Public Property Country() As Global.System.String
			Get
				Return _Country
			End Get
			Set(ByVal value As System.String)
				OnCountryChanging(value)
				ReportPropertyChanging("Country")
				_Country = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("Country")
				OnCountryChanged()
			End Set
		End Property
		Private _Country As Global.System.String
		Partial Private Sub OnCountryChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnCountryChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
		Public Property Phone() As Global.System.String
			Get
				Return _Phone
			End Get
			Set(ByVal value As System.String)
				OnPhoneChanging(value)
				ReportPropertyChanging("Phone")
				_Phone = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("Phone")
				OnPhoneChanged()
			End Set
		End Property
		Private _Phone As Global.System.String
		Partial Private Sub OnPhoneChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnPhoneChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
		Public Property Fax() As Global.System.String
			Get
				Return _Fax
			End Get
			Set(ByVal value As System.String)
				OnFaxChanging(value)
				ReportPropertyChanging("Fax")
				_Fax = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("Fax")
				OnFaxChanged()
			End Set
		End Property
		Private _Fax As Global.System.String
		Partial Private Sub OnFaxChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnFaxChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
		Public Property HomePage() As Global.System.String
			Get
				Return _HomePage
			End Get
			Set(ByVal value As System.String)
				OnHomePageChanging(value)
				ReportPropertyChanging("HomePage")
				_HomePage = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("HomePage")
				OnHomePageChanged()
			End Set
		End Property
		Private _HomePage As Global.System.String
		Partial Private Sub OnHomePageChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnHomePageChanged()
		End Sub

		#End Region


	End Class

	#End Region


End Namespace
